### ISSUE TITLE
Error: could not find target field: public static org.jooq.DDLQuery io.quarkiverse.jooq.runtime.graal.ParserImplSubstitutions.IGNORE after update 0.2.0 -> 0.2.1

### ISSUE THREAD

**Issue by lenalebt** [quarkiverse/quarkus-jooq#27]
Hey,

I'm currently getting this error when using 0.2.1 together with jooq 3.15.1 when building native images. JVM mode works. Enforcing the jooq version to 3.14.9 fixes the issue, version 3.15.0 also is problematic (which is the one used in 0.2.1 of quarkus-jooq).

It seems that there are two new functions on classes implemented for `DDLQuery` and `Query`? I'm not very deep into this, but it seems that's where the issue may come from - at least when having a look, my IDE was screaming at me to implement two methods. I can't get it back to show me that problem, but it was about `getSQL(Boolean)` I think?

```
Error: could not find target field: public static org.jooq.DDLQuery io.quarkiverse.jooq.runtime.graal.ParserImplSubstitutions.IGNORE
com.oracle.svm.core.util.UserError$UserException: could not find target field: public static org.jooq.DDLQuery io.quarkiverse.jooq.runtime.graal.ParserImplSubstitutions.IGNORE
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalField(AnnotationSubstitutionProcessor.java:757)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:429)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:343)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:309)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:929)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

Is this know already, or any known workarounds besides downgrading?

**Comment by lukaseder** [comment]
Perhaps, rather than fixing this in third parties like quarkus-jooq, we can fix this for good in jOOQ directly? I've created https://github.com/jOOQ/jOOQ/issues/12222, which will be fixed in jOOQ 3.16.0, 3.15.2, and 3.14.14

**Comment by lenalebt** [comment]
Sounds like a good idea to me :). In the meantime, I can live with a downgrade - I don't necessarily need the new features right now.

**Comment by lukaseder** [comment]
While we're at it: Is there an easy way to find all the other workarounds you folks had to apply because of these reasons? jOOQ will eventually get integration tested out of the box in an AOP environment, but we're not there yet. In the meantime, I could simplify your lives by removing more unnecessary reflection usage... After all, these are undocumented internals, and they'll break between any patch release. One obvious candidate is `DefaultConverterProvider`'s reflective dependency on Jackson/Gson

**Comment by angrymango** [comment]
@lenalebt please can you try upgrading to v0.2.2 which fixes the native compilation issue. I'm also about to release v0.3.0 which will support Quarkus 2.0.3.Final.

**Comment by angrymango** [comment]
@lukaseder the only other reflection based workaround I had to put in place to make native compilation work was in org.jooq.impl.DefaultRecordMapper inner class ProxyMapper:

```java
package io.quarkiverse.jooq.runtime.graal;

import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;

@TargetClass(className = "org.jooq.impl.DefaultRecordMapper", innerClass = "ProxyMapper")
public final class DefaultRecordMapperSubstitutions<E> {
    @Substitute
    private E proxy() {
        return null;
    }
}
```

**Comment by lenalebt** [comment]
@angrymango can confirm it working with 0.2.2, thanks for the fix :)!

**Comment by lukaseder** [comment]
> @lukaseder the only other reflection based workaround I had to put in place to make native compilation work was in org.jooq.impl.DefaultRecordMapper inner class ProxyMappe

Thanks for the hint. I guess that one can't be removed easily, as reflection is the feature here, not a means to an end. At least that won't change soon, so there's not much risk for breaking things.
